### PR TITLE
Updates to use traction/multitenancy

### PR DESCRIPTION
**Pull request by ianco**
Refactored code that calls aca-py to make the transition to traction a bit more straightforward

Runs in aca-py or traction mode.  Currently traction runs in "single tenant" mode, with default tenant created on startup.  Multi-tenancy will be in the next update.

See https://hackmd.io/LbDlqU-9Q0mcGnBXg_hYRw?view

### CODE REVIEW

**Review by esune — APPROVED** [review]
Looks great!

I have not had a chance to run the code on my machine, I might try later on out of curiosity, but I am not sure when I am going to be able to get to it unfortunately.

**Comment by ianco** [comment]
> Looks great!
> 
> I have not had a chance to run the code on my machine, I might try later on out of curiosity, but I am not sure when I am going to be able to get to it unfortunately.

@swcurran would be great if you could give it a go!

**Comment by swcurran** [comment]
I'll try -- but don't wait on me.

**Comment by swcurran** [comment]
OK - looked easy to try, but on my Linux system, I got this error trying to build traction. I assume I should report this on the traction repo?  I'm guessing this is a docker-compose version issue.  I'm running: docker-compose version 1.29.0, build 07737305, which is pretty much up to date.

```
ERROR: The Compose file './docker-compose.yml' is invalid because:
services.endorser-agent.ports contains an invalid type, it should be a number, or an object
services.endorser-agent.ports contains an invalid type, it should be a number, or an object
services.traction-agent.ports contains an invalid type, it should be a number, or an object
services.traction-agent.ports contains an invalid type, it should be a number, or an object
services.endorser-api.ports contains an invalid type, it should be a number, or an object
services.traction-api.ports contains an invalid type, it should be a number, or an object
services.endorser-db.ports contains an invalid type, it should be a number, or an object
services.traction-db.ports contains an invalid type, it should be a number, or an object
services.endorser-agent.ports value [':', ':'] has non-unique elements
services.traction-agent.ports value [':', ':'] has non-unique elements
```

**Comment by swcurran** [comment]
Question -- are we better to make a new repo "issuer-kit-traction", or to have this repo support both a traction and non-traction mode?  In other words, do we create a new traction-based service, deprecate the existing and migrate (as we want) the existing deployments to the new traction base?

Related question -- are you thinking we will define a way to deploy a new "issuer-kit-tenant" on a traction instance via some sort of admin "New" command (in a GUI?) and then updating a config persisted in Traction, so we can deploy a new kit instance without using GitHub?  Not necessarily needed -- I'm just spitballin' to understand.  It opens up a lot of questions :-)

**Comment by ianco** [comment]
> OK - looked easy to try, but on my Linux system, I got this error (after the warnings) trying to build traction. I assume I should report this on the traction repo? I'm guessing this is a docker-compose version issue. I'm running: docker-compose version 1.29.0, build 07737305, which is pretty much up to date.
> 
> Or perhaps it is because I have no env variables set?

You have to `cp .env-example .env` (in the scripts directory), it should be in the docs somewhere ...

https://github.com/bcgov/traction/tree/develop/scripts#start

Aha I see that the docs are incorrect :-(  (`.env` *not* `.env.local`)

**Comment by ianco** [comment]
> Question -- are we better to make a new repo "issuer-kit-traction", or to have this repo support both a traction and non-traction mode? In other words, do we create a new traction-based service, deprecate the existing and migrate (as we want) the existing deployments to the new traction base?

Good question - I don't think it makes sense to have 2 separate repo's, most if the Issuer Kit code will be the same regardless of aca-py vs traction.

Rather ... does it make sense to maintain a single-tenant version of Issuer Kit once we have implemented multitenancy?  And if so does it make sense to use aca-py, or to use Traction (the way it is implemented now)?

> Related question -- are you thinking we will define a way to deploy a new "issuer-kit-tenant" on a traction instance via some sort of admin "New" command (in a GUI?) and then updating a config persisted in Traction, so we can deploy a new kit instance without using GitHub? Not necessarily needed -- I'm just spitballin' to understand. It opens up a lot of questions :-)

This is covered in the hackmd doc (I think, if I understand your question) - we would have a single deployment if Issuer Kit (with Traction) and we would have an admin function (api or UI) to create a new "Issuer Kit Instance" which would just be a tenant in the "Issuer Kit Deployment".  The trick here is for the Admin and Issuer UI's to know which "instance" (or wallet) they are dealing with.  This is a security question that we still need to solve ...

**Comment by swcurran** [comment]
Sorry -- I confess I hadn't looked at the hackmd document.  I've given it a quick pass and will spend some more time on it and respond.

**Comment by ianco** [comment]
> Sorry -- I confess I hadn't looked at the hackmd document. I've given it a quick pass and will spend some more time on it and respond.

No rush, it may make sense for you Emiliano & I to talk through it

**Pull request closed without merging**
