### PR TITLE
Update Lissi wallet instructions

### PR DESCRIPTION
**Pull request by opleno**
I just downloaded the app. I did not need any further configuration before scanning Faber's QR invitation (https://github.com/hyperledger/aries-cloudagent-python/blob/main/demo/AliceGetsAPhone.md#run-an-instance-of-indy-tails-server). The election of the network probably happens automatically.

### CODE REVIEW

**Comment by swcurran** [comment]
Thanks!  Happy to merge, but the DCO needs to be updated.  DCO - Developer Certificate of Origin - https://github.com/apps/dco. if you can do that, we can merge.

**Comment by esune** [comment]
@opleno would you be able to amend your commits to include DCO? We cannot merge the PR otherwise.

**Comment by opleno** [comment]
Yes, I added this commit in a rush because I had a big trip on March 15th so sorry for that.
I am not a git expert yet (as you probably noticed), a little help on how to proceed would be appreciated: should we start a new branch where I can commit with --signoff or is there any way to reuse "patch-1" and commit changes with "-s"? For me, the first option is easier. Thanks

**Comment by WadeBarnes** [comment]
@opleno, try following the examples here; https://github.com/bcgov/issuer-kit/pull/349/checks?check_run_id=5538609065

**Comment by opleno** [comment]
@WadeBarnes following the instructions, I am able to rebase succesfully but when trying to "git push --force-with-lease origin patch-1" (step 3), I get a 403 forbidden error. Branch "patch-1" is not published (not accessible with "git branch -r"), could this be the reason the 403 error?

**Comment by WadeBarnes** [comment]
@opleno, It looks like you were able to update the branch, but the commit message still does not contain the sign-off.  You can see the current comment message here; https://github.com/bcgov/issuer-kit/pull/349/commits/f92339ffb580f489b3bab6ee336a1626d8d62cbe

**Comment by WadeBarnes** [comment]
@opleno, Yes, you can start fresh with a new branch and a new PR.

**Comment by opleno** [comment]
Great, so please let me ask before doing any change, because I am mostly used to Bitbucket. 
I assume I should create a new issue in the project, then create a bugfix branch somehow linked to that issue, commit the signed off changes, merge and create PR. Is it possible in Github to create the bugfix branch using a GUI like in Bitbucket? Otherwise, I can just create a "bugfix/name". Is there a naming convention? (Sorry for my lack of experience in contributing to open source code)

**Comment by opleno** [comment]
I do also see [here](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue) that the commit/PR can be linked to an issue using a keyword

**Pull request closed without merging**
