### PR TITLE
Wallet Seed environment variable consistency

### PR DESCRIPTION
**Pull request by sgroh**
Adding ACAPY_WALLET_SEED environment variable on the manage script and it's usage on the docker-compose Issuer Kit Agent section.

Updating README file with the introduced ACAPY_WALLET_SEED environment variable.

### CODE REVIEW

**Review by esune — APPROVED** [review]

**Review by esune — CHANGES_REQUESTED** [review]
@sgroh we need DCO for commits pushed to this repository: can you please fix the commit history and add it? Changes look otherwise good to me.

**Comment by sgroh** [comment]
> @sgroh we need DCO for commits pushed to this repository: can you please fix the commit history and add it? Changes look otherwise good to me.

Sure, done.

**Comment by esune** [comment]
> > @sgroh we need DCO for commits pushed to this repository: can you please fix the commit history and add it? Changes look otherwise good to me.
> 
> Sure, done.

It looks like the check is still not passing. You will need to either update your public profile to use your full name as display name, or use your GitHub handle in the DCO sign-off - the check will verify both name and email match.

**Comment by sgroh** [comment]
> > > @sgroh we need DCO for commits pushed to this repository: can you please fix the commit history and add it? Changes look otherwise good to me.
> > 
> > 
> > Sure, done.
> 
> It looks like the check is still not passing. You will need to either update your public profile to use your full name as display name, or use your GitHub handle in the DCO sign-off - the check will verify both name and email match.

My bad yes sure, it's already fixed. github DCO was not enabled, I've added it manually prior my last change. It's fixed now it should match.

**Review by esune — APPROVED** [review]

**Pull request merged**
